project:
  title: "OpenSciency Introductory Resources on Open Science"
  type: book
  output-dir: docs

book:
  author: "Almarzouq, Batool; Azevedo, Flavio; Batalha, Natasha; Bayer, Johanna; Bell, Tomo; Bhogal, Saranjeet; Black, Melissa; Brown, Sierra; Campitelli, Elio; Chegini, Taher; Dunleavy, Daniel; Ee, Yeo Keat; El-Gebali, Sara; Erdmann, Christopher; Ferdush, Jannatul; Fouilloux, Anne; Hall, Siobhan Mackenzie; Kherroubi Garcia, Ismael; Klusza, Stephen; Lacerda, Michel; Medina-Smith, Andrea; Meireles, Mariana; Muhammad, Shamsuddeen; Onabajo, Babatunde; Osman, Amber; Papadopoulou, Elli; Pauline, Karega; Plomp, Esther; Rao, Douglas; Ringuette, Rebecca; Saderi, Daniela; Shanahan, Hugh; Sharan, Malvika; Silan, Miguel; Sundukova, Mayya; Swetnam, Tyson; Vaz, Ana; Yehudi, Yo"
  date: "22/02/2022"
  page-navigation: true
  favicon: logo.png
  search: true
  repo-url: https://github.com/opensciency
  chapters:
    - index.md
    - part: ethos-of-open/lesson1-intro-to-open-science.md
      chapters:
        - ethos-of-open/lesson2-benefits-challenges-of-open.md
        - ethos-of-open/lesson3-open-stakeholders.md
        - ethos-of-open/lesson4-impact-of-open.md
        - ethos-of-open/lesson5-how.md
        - ethos-of-open/eoo-authors.md
    - part: open-software/lesson0-preamble.md
      chapters:
        - open-software/lesson1-introduction.md
        - open-software/lesson2-pros-cons.md
        - open-software/lesson3-licensing.md
        - open-software/lesson4-code-management.md
        - open-software/lesson5-vesion-control.md
        - open-software/lesson6-contribution.md
        - open-software/os-authors.md
    - part: open-data/Lesson1-WhatIsOpenData.md
      chapters: 
        - open-data/Lesson2-Benefits.md
        - open-data/Lesson3-Responsible.md
        - open-data/Lesson4-CARE&FAIR.md
        - open-data/Lesson5-Planning.md
        - open-data/od-authors.md
        - open-data/Appendix.md
    - part: open-results/README.md
      chapters: 
        - open-results/lesson1-research-process-and-results.md
        - open-results/lesson2-results-and-open-science.md
        - open-results/lesson3-apply-open-results.md
        - open-results/lesson4-opportunities-and-credits.md
        - open-results/or-authors.md
    - part: open-tools-resources/lesson1-intro-open-science-tools.md
      chapters: 
        - open-tools-resources/lesson2-tools-across-research-lifecycle.md
        - open-tools-resources/lesson3-tools-for-reproducibility.md
        - open-tools-resources/lesson4-practicing-team-open-science.md
        - open-tools-resources/lesson5-open-science-communities.md
        - open-tools-resources/otr-authors.md

toc: true
number-sections: false
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport
  epub:
    cover-image:

editor:
  render-on-save: true